import { addDays, formatISO, setHours, setMinutes, startOfDay, subDays } from "date-fns";

import { type DemoDatabase } from "@/lib/demo/types";

const ids = {
  admin: "11111111-1111-4111-8111-111111111111",
  providerProfile: "22222222-2222-4222-8222-222222222222",
  coordinator: "33333333-3333-4333-8333-333333333333",
  patientProfile: "44444444-4444-4444-8444-444444444444",
  provider: "55555555-5555-4555-8555-555555555555",
  patient: "66666666-6666-4666-8666-666666666666",
  appointmentToday: "77777777-7777-4777-8777-777777777777",
  appointmentUpcoming: "88888888-8888-4888-8888-888888888888",
  appointmentPast: "99999999-9999-4999-8999-999999999999",
  encounter: "aaaaaaa1-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
  note: "bbbbbbb1-bbbb-4bbb-8bbb-bbbbbbbbbbb1",
  carePlan: "ccccccc1-cccc-4ccc-8ccc-ccccccccccc1",
  thread: "ddddddd1-dddd-4ddd-8ddd-ddddddddddd1",
  message1: "eeeeeee1-eeee-4eee-8eee-eeeeeeeeeee1",
  message2: "fffffff1-ffff-4fff-8fff-fffffffffff1",
};

export function buildDemoDatabase(): DemoDatabase {
  const today = startOfDay(new Date());
  const todayVisitStart = setMinutes(setHours(today, 10), 0);
  const todayVisitEnd = setMinutes(setHours(today, 10), 30);
  const upcomingStart = setMinutes(setHours(addDays(today, 2), 14), 0);
  const upcomingEnd = setMinutes(setHours(addDays(today, 2), 14), 30);
  const pastStart = setMinutes(setHours(subDays(today, 3), 9), 30);
  const pastEnd = setMinutes(setHours(subDays(today, 3), 10), 0);

  return {
    organization: {
      id: "00000000-0000-4000-8000-000000000001",
      name: "Luma Virtual Care",
      slug: "luma-virtual-care",
      timezone: "America/New_York",
      contactEmail: "ops@luma.health",
    },
    profiles: [
      {
        id: ids.admin,
        firstName: "Amelia",
        lastName: "Reed",
        email: "admin@luma.health",
        phone: "2125550100",
        role: "admin",
        title: "Operations Director",
      },
      {
        id: ids.providerProfile,
        firstName: "Dylan",
        lastName: "Park",
        email: "provider@luma.health",
        phone: "2125550110",
        role: "provider",
        title: "MD",
        specialty: "Family Medicine",
      },
      {
        id: ids.coordinator,
        firstName: "Nina",
        lastName: "Flores",
        email: "care@luma.health",
        phone: "2125550120",
        role: "care_coordinator",
        title: "RN",
      },
      {
        id: ids.patientProfile,
        firstName: "Jordan",
        lastName: "Lee",
        email: "patient@luma.health",
        phone: "9175550199",
        role: "patient",
      },
    ],
    providers: [
      {
        id: ids.provider,
        profileId: ids.providerProfile,
        specialty: "Family Medicine",
        credentials: "MD",
        bio: "Virtual-first primary care with a focus on preventive medicine and longitudinal care.",
        isAcceptingNewPatients: true,
      },
    ],
    patients: [
      {
        id: ids.patient,
        profileId: ids.patientProfile,
        primaryProviderId: ids.provider,
        mrn: "PT-0001",
        firstName: "Jordan",
        lastName: "Lee",
        dateOfBirth: "1991-05-14",
        sex: "Female",
        genderIdentity: "Woman",
        email: "patient@luma.health",
        phone: "9175550199",
        addressLine1: "245 Park Avenue",
        city: "New York",
        state: "NY",
        postalCode: "10017",
        medicalHistorySummary: "Mild intermittent asthma, seasonal allergies, prior iron deficiency anemia.",
        insuranceNotes: "PPO plan on file. Eligibility not yet automated.",
        consentAcknowledged: true,
        intakeStatus: "completed",
        lastIntakeSubmittedAt: formatISO(subDays(today, 7)),
      },
    ],
    patientContacts: [
      {
        id: "12121212-1212-4121-8121-121212121212",
        patientId: ids.patient,
        fullName: "Avery Lee",
        relationship: "Spouse",
        phone: "9175550101",
        email: "avery.lee@example.com",
        isEmergencyContact: true,
      },
    ],
    insurance: [
      {
        id: "13131313-1313-4131-8131-131313131313",
        patientId: ids.patient,
        providerName: "Blue Horizon Health",
        planName: "PPO Gold",
        memberId: "BH-4440021",
        groupNumber: "70214",
        coverageNotes: "In-network for primary care, referral not required.",
      },
    ],
    allergies: [
      {
        id: "14141414-1414-4141-8141-141414141414",
        patientId: ids.patient,
        allergen: "Penicillin",
        reaction: "Rash",
        severity: "Moderate",
        notes: "Occurred in adolescence.",
      },
    ],
    medications: [
      {
        id: "15151515-1515-4151-8151-151515151515",
        patientId: ids.patient,
        name: "Albuterol inhaler",
        dose: "90 mcg",
        frequency: "As needed",
        route: "Inhaled",
        status: "Active",
        prescribedBy: "Dylan Park, MD",
      },
    ],
    availability: [
      {
        id: "16161616-1616-4161-8161-161616161616",
        providerId: ids.provider,
        weekday: 1,
        startTime: "09:00",
        endTime: "17:00",
        locationName: "Virtual",
        visitMode: "virtual",
      },
      {
        id: "17171717-1717-4171-8171-171717171717",
        providerId: ids.provider,
        weekday: 3,
        startTime: "09:00",
        endTime: "15:00",
        locationName: "Virtual",
        visitMode: "virtual",
      },
    ],
    appointments: [
      {
        id: ids.appointmentToday,
        patientId: ids.patient,
        providerId: ids.provider,
        appointmentType: "Follow-up",
        visitReason: "Fatigue review and preventive care plan",
        locationName: "Virtual visit",
        scheduledStart: formatISO(todayVisitStart),
        scheduledEnd: formatISO(todayVisitEnd),
        status: "confirmed",
        reminderStatus: "sent",
      },
      {
        id: ids.appointmentUpcoming,
        patientId: ids.patient,
        providerId: ids.provider,
        appointmentType: "Chronic care",
        visitReason: "Asthma symptom check-in",
        locationName: "Virtual visit",
        scheduledStart: formatISO(upcomingStart),
        scheduledEnd: formatISO(upcomingEnd),
        status: "scheduled",
        reminderStatus: "pending",
      },
      {
        id: ids.appointmentPast,
        patientId: ids.patient,
        providerId: ids.provider,
        appointmentType: "Annual wellness",
        visitReason: "Wellness review",
        locationName: "Virtual visit",
        scheduledStart: formatISO(pastStart),
        scheduledEnd: formatISO(pastEnd),
        status: "completed",
        reminderStatus: "sent",
      },
    ],
    encounters: [
      {
        id: ids.encounter,
        appointmentId: ids.appointmentPast,
        patientId: ids.patient,
        providerId: ids.provider,
        status: "completed",
        chiefComplaint: "Persistent fatigue",
        visitSummary: "Reviewed recent fatigue, sleep routine, and inhaler usage. Ordered repeat labs and reinforced hydration and nutrition goals.",
        shareableWithPatient: true,
        startedAt: formatISO(pastStart),
        completedAt: formatISO(pastEnd),
      },
    ],
    soapNotes: [
      {
        id: ids.note,
        encounterId: ids.encounter,
        subjective: "Patient reports 3 weeks of fatigue, otherwise denies chest pain or shortness of breath.",
        objective: "Virtual exam notable for comfortable appearance, no respiratory distress, speaking in full sentences.",
        assessment: "Likely multifactorial fatigue with contributing sleep disruption and iron deficiency history.",
        plan: "Repeat CBC, ferritin, and CMP. Encourage hydration, sleep schedule, and follow-up in 2 weeks.",
        followUp: "Return sooner for worsening dyspnea, dizziness, or syncope.",
        signedAt: formatISO(addDays(pastEnd, 0)),
      },
    ],
    diagnoses: [
      {
        id: "18181818-1818-4181-8181-181818181818",
        encounterId: ids.encounter,
        patientId: ids.patient,
        code: "R53.83",
        title: "Other fatigue",
        status: "Active",
        notes: "Monitoring with interval labs.",
      },
    ],
    vitalSigns: [
      {
        id: "19191919-1919-4191-8191-191919191919",
        encounterId: ids.encounter,
        patientId: ids.patient,
        recordedAt: formatISO(pastStart),
        systolicBp: 118,
        diastolicBp: 74,
        heartRate: 72,
        weightLb: 146,
        bmi: 23.4,
        temperatureF: 98.6,
      },
    ],
    carePlans: [
      {
        id: ids.carePlan,
        patientId: ids.patient,
        encounterId: ids.encounter,
        goal: "Improve daytime energy and symptom stability over the next 6 weeks.",
        interventions: "Hydration target, repeat iron studies, weekly exercise ramp, inhaler review.",
        milestones: "Lab review completed, symptoms logged twice weekly, 150 minutes activity target.",
        status: "active",
        assignedTo: ids.providerProfile,
        shareWithPatient: true,
        nextReviewAt: formatISO(addDays(today, 14)),
      },
    ],
    documents: [
      {
        id: "20202020-2020-4202-8202-202020202020",
        patientId: ids.patient,
        encounterId: ids.encounter,
        title: "Visit Summary - Annual Wellness",
        documentType: "visit_summary",
        mimeType: "application/pdf",
        isShareable: true,
      },
    ],
    threads: [
      {
        id: ids.thread,
        patientId: ids.patient,
        ownerProfileId: ids.coordinator,
        subject: "Lab scheduling follow-up",
        priority: "routine",
        status: "open",
        lastMessageAt: formatISO(subDays(today, 1)),
      },
    ],
    messages: [
      {
        id: ids.message1,
        threadId: ids.thread,
        senderProfileId: ids.coordinator,
        body: "We have your lab order ready. Would Monday morning work for your blood draw?",
        sentAt: formatISO(subDays(today, 1)),
      },
      {
        id: ids.message2,
        threadId: ids.thread,
        senderProfileId: ids.patientProfile,
        body: "Yes, Monday morning works for me. Thank you.",
        sentAt: formatISO(subDays(today, 1)),
        readAt: formatISO(subDays(today, 1)),
      },
    ],
    auditLogs: [
      {
        id: "21212121-2121-4212-8212-212121212121",
        actorProfileId: ids.providerProfile,
        entityType: "soap_note",
        entityId: ids.note,
        action: "soap_note.signed",
        details: { encounterId: ids.encounter },
        createdAt: formatISO(pastEnd),
      },
    ],
  };
}

